# common/tasks/main.yml

- name: Update apk packages
  apk:
    update_cache: yes

- name: Install Python3 and pip
  apk:
    name:
      - python3
      - py3-pip
    state: present

- name: Install Flask
  pip:
    name: flask
    executable: pip3
